# Generated by Django 4.1.2 on 2022-10-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='unique_id',
        ),
    ]
