# Generated by Django 4.1.2 on 2022-10-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profiles_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subscribed_since',
            field=models.DateField(auto_now_add=True, default='2022-11-11'),
            preserve_default=False,
        ),
    ]
